# These are some functions often required in parallel foreach loops. 
# They can be sourced within the function called by the foreach statement. 
# 
###############################################################################


## some functions describing bits of the model.
## total eggs per gram as a function of mean worm burden.  
epgPerPerson <- function(M, p)
{
	return(p$lambda*M*p$z*(1+M*(1-p$z)/p$k)^(-p$k-1))
}

## multiplicative fertility correction factor to be applied to the mean eggs per person function. 
## See equation 16.22 in A&M and Appendix H for the classic derivation. 
## this is a slightly different version for a model with females only and assuming a density-dependence on female worm population (see notes in notebook for derivation). 
fertilityFunc <- function(M, p)
{
	a <- 1 + M*(1 - p$z)/p$k
	b <- 1 + 2*M/p$k - p$z*M/p$k
	return(1 - (a/b)^(p$k+1))
}

## Run monogParams <- monogFertilityConfig(params) before using monogamous fertility functions 
## to generate necessary global variables. 
## This function is a function of k only. 
monogFertilityConfig <- function(p,N=30)
{
	## p is a list of parameters containing at least p$k. 
	#N <- 200  ## sufficient resolution for the numerical integration, I found. YOU TUNED THIS NUMBER AND THEN FORGOT TO INCLUDE IT! 
	k <- p$k
	c_k <- gamma(k+0.5)*(2*k/pi)^0.5/gamma(k+1) 
	cosTheta <- cos(seq(from=0,to=2*pi,length.out=N+1)[1:N])
	return(list(c_k=c_k,cosTheta=cosTheta))
}

## Fertility factor for monogamously mating worms.See A&M table 16.1 and also equation 2.15 of May '77 [doi: 10.1016/0025-5564(77)90030-X] 
## and in Appendix A for the approximation used (A.18). Boundary for change between approx and exact is 'empirical'. 
monogFertilityFuncApprox <- function(mValue,p)
{
	## Requires a list called monogParams in the params list generated by the line: 
	## params$monogParams <- monogFertilityConfig(params) or similar
	if(mValue > 25*p$k)
	{
		## The approximation for m?m is small...
		return(1-p$monogParams$c_k/sqrt(mValue))
	} else
	{
		## integral summation. If this is inaccurate, check sensitivity to discretization of integrand. 
		gValue <- mValue/(mValue+p$k)
		integrand <- (1-p$monogParams$cosTheta)*(1+gValue*p$monogParams$cosTheta)^(-1-p$k)
		integral <- mean(integrand)
		return(1 - (1-gValue)^(1+p$k)*integral)
	}
}


## generation of eggs with monogamous reproduction taken into account. 
epgMonog <- function(M,p)
{
	matingProbs <- sapply(M,monogFertilityFuncApprox,p=p)
	#matingProbs <- foreach(x=M,.combine=c,.export=c("monogFertilityFuncApprox","monogParams")) %do% monogFertilityFuncApprox(x,p) ## parallelizable version. DOESN'T HELP.
	return(epgPerPerson(M,p)*matingProbs)
}


## generation of eggs with sexual reproduction taken into account. 
epgFertility <- function(M,p) 
{
	return(epgPerPerson(M,p)*fertilityFunc(M,p))
}
